backend:
  name: git-gateway
  branch: main

media_folder: static/images
public_folder: ../../static/images/

collection:
  - name: "travel-packages"
  preview: false;
  label: "Travel Packages"
  folder: "content/travel-packages"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Location", name: "location", widget: "string" }
    - { label: "Travel Dates", name: "travel-dates", widget: "string"}
    - { label: "Featured Images", name: featured-images, widget: image }
    - { label: "Body", name: body, widget: "markdown" }